"use client"

import Image from 'next/image'
import type { NextPage } from "next";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";
export default function Home() {
  return (
  <div>
   <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main >
       <Sidebar/>
        <Feed/>
        <Widgets/>
    </main>
  </div>
    
  )
}
